# Generated by Django 6.1 on 2026-09-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='old Author', max_length=255),
        ),
    ]
